import { Match } from '../types';

export const stageLabels: Record<string, string> = {
  group: 'Fase de Grupos',
  round16: 'Octavos',
  quarter: 'Cuartos',
  semi: 'Semifinal',
  final: 'Final',
};

export const groupNames = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'];

export const MATCHES: Match[] = [
  {
    "id": "1",
    "date": "2026-06-11",
    "time": "15:00",
    "homeTeam": "México",
    "awayTeam": "Sudáfrica",
    "group": "Grupo A",
    "stadium": "Estadio Ciudad de México",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "2",
    "date": "2026-06-11",
    "time": "22:00",
    "homeTeam": "República de Corea",
    "awayTeam": "República Checa",
    "group": "Grupo A",
    "stadium": "Estadio Guadalajara",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "3",
    "date": "2026-06-12",
    "time": "15:00",
    "homeTeam": "Canadá",
    "awayTeam": "Bosnia y Herzegovina",
    "group": "Grupo B",
    "stadium": "Estadio Toronto",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "4",
    "date": "2026-06-12",
    "time": "21:00",
    "homeTeam": "Estados Unidos",
    "awayTeam": "Paraguay",
    "group": "Grupo D",
    "stadium": "Estadio Los Ángeles",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "5",
    "date": "2026-06-13",
    "time": "15:00",
    "homeTeam": "Catar",
    "awayTeam": "Suiza",
    "group": "Grupo B",
    "stadium": "Estadio Bahía de San Francisco",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "6",
    "date": "2026-06-13",
    "time": "18:00",
    "homeTeam": "Brasil",
    "awayTeam": "Marruecos",
    "group": "Grupo C",
    "stadium": "Estadio Nueva York Nueva Jersey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "7",
    "date": "2026-06-13",
    "time": "21:00",
    "homeTeam": "Haití",
    "awayTeam": "Escocia",
    "group": "Grupo C",
    "stadium": "Estadio Boston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "8",
    "date": "2026-06-13",
    "time": "00:00",
    "homeTeam": "Australia",
    "awayTeam": "Turquía",
    "group": "Grupo D",
    "stadium": "Estadio BC Place Vancouver",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "9",
    "date": "2026-06-14",
    "time": "13:00",
    "homeTeam": "Alemania",
    "awayTeam": "Curazao",
    "group": "Grupo E",
    "stadium": "Estadio Houston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "10",
    "date": "2026-06-14",
    "time": "16:00",
    "homeTeam": "Países Bajos",
    "awayTeam": "Japón",
    "group": "Grupo F",
    "stadium": "Estadio Dallas",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "11",
    "date": "2026-06-14",
    "time": "19:00",
    "homeTeam": "Costa de Marfil",
    "awayTeam": "Ecuador",
    "group": "Grupo E",
    "stadium": "Estadio Filadelfia",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "12",
    "date": "2026-06-14",
    "time": "22:00",
    "homeTeam": "Suecia",
    "awayTeam": "Túnez",
    "group": "Grupo F",
    "stadium": "Estadio Monterrey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "13",
    "date": "2026-06-15",
    "time": "12:00",
    "homeTeam": "España",
    "awayTeam": "Cabo Verde",
    "group": "Grupo H",
    "stadium": "Estadio Atlanta",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "14",
    "date": "2026-06-15",
    "time": "15:00",
    "homeTeam": "Bélgica",
    "awayTeam": "Egipto",
    "group": "Grupo G",
    "stadium": "Estadio Seattle",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "15",
    "date": "2026-06-15",
    "time": "18:00",
    "homeTeam": "Arabia Saudí",
    "awayTeam": "Uruguay",
    "group": "Grupo H",
    "stadium": "Estadio Miami",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "16",
    "date": "2026-06-15",
    "time": "21:00",
    "homeTeam": "Irán",
    "awayTeam": "Nueva Zelanda",
    "group": "Grupo G",
    "stadium": "Estadio Los Ángeles",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "17",
    "date": "2026-06-16",
    "time": "15:00",
    "homeTeam": "Francia",
    "awayTeam": "Senegal",
    "group": "Grupo I",
    "stadium": "Estadio Nueva York Nueva Jersey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "18",
    "date": "2026-06-16",
    "time": "18:00",
    "homeTeam": "Irak",
    "awayTeam": "Noruega",
    "group": "Grupo I",
    "stadium": "Estadio Boston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "19",
    "date": "2026-06-16",
    "time": "21:00",
    "homeTeam": "Argentina",
    "awayTeam": "Argelia",
    "group": "Grupo J",
    "stadium": "Estadio Kansas City",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "20",
    "date": "2026-06-16",
    "time": "00:00",
    "homeTeam": "Austria",
    "awayTeam": "Jordania",
    "group": "Grupo J",
    "stadium": "Estadio Bahía de San Francisco",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "21",
    "date": "2026-06-17",
    "time": "13:00",
    "homeTeam": "Portugal",
    "awayTeam": "RD Congo",
    "group": "Grupo K",
    "stadium": "Estadio Houston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "22",
    "date": "2026-06-17",
    "time": "16:00",
    "homeTeam": "Inglaterra",
    "awayTeam": "Croacia",
    "group": "Grupo L",
    "stadium": "Estadio Dallas",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "23",
    "date": "2026-06-17",
    "time": "19:00",
    "homeTeam": "Ghana",
    "awayTeam": "Panamá",
    "group": "Grupo L",
    "stadium": "Estadio Toronto",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "24",
    "date": "2026-06-17",
    "time": "22:00",
    "homeTeam": "Uzbekistán",
    "awayTeam": "Colombia",
    "group": "Grupo K",
    "stadium": "Estadio Ciudad de México",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "25",
    "date": "2026-06-18",
    "time": "12:00",
    "homeTeam": "República Checa",
    "awayTeam": "Sudáfrica",
    "group": "Grupo A",
    "stadium": "Estadio Atlanta",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "26",
    "date": "2026-06-18",
    "time": "15:00",
    "homeTeam": "Suiza",
    "awayTeam": "Bosnia y Herzegovina",
    "group": "Grupo B",
    "stadium": "Estadio Los Ángeles",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "27",
    "date": "2026-06-18",
    "time": "18:00",
    "homeTeam": "Canadá",
    "awayTeam": "Catar",
    "group": "Grupo B",
    "stadium": "Estadio BC Place Vancouver",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "28",
    "date": "2026-06-18",
    "time": "21:00",
    "homeTeam": "México",
    "awayTeam": "República de Corea",
    "group": "Grupo A",
    "stadium": "Estadio Guadalajara",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "29",
    "date": "2026-06-19",
    "time": "15:00",
    "homeTeam": "Estados Unidos",
    "awayTeam": "Australia",
    "group": "Grupo D",
    "stadium": "Estadio Seattle",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "30",
    "date": "2026-06-19",
    "time": "18:00",
    "homeTeam": "Escocia",
    "awayTeam": "Marruecos",
    "group": "Grupo C",
    "stadium": "Estadio Boston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "31",
    "date": "2026-06-19",
    "time": "21:00",
    "homeTeam": "Brasil",
    "awayTeam": "Haití",
    "group": "Grupo C",
    "stadium": "Estadio Filadelfia",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "32",
    "date": "2026-06-19",
    "time": "00:00",
    "homeTeam": "Turquía",
    "awayTeam": "Paraguay",
    "group": "Grupo D",
    "stadium": "Estadio Bahía de San Francisco",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "33",
    "date": "2026-06-20",
    "time": "13:00",
    "homeTeam": "Países Bajos",
    "awayTeam": "Suecia",
    "group": "Grupo F",
    "stadium": "Estadio Houston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "34",
    "date": "2026-06-20",
    "time": "16:00",
    "homeTeam": "Alemania",
    "awayTeam": "Costa de Marfil",
    "group": "Grupo E",
    "stadium": "Estadio Toronto",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "35",
    "date": "2026-06-20",
    "time": "22:00",
    "homeTeam": "Ecuador",
    "awayTeam": "Curazao",
    "group": "Grupo E",
    "stadium": "Estadio Kansas City",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "36",
    "date": "2026-06-20",
    "time": "00:00",
    "homeTeam": "Túnez",
    "awayTeam": "Japón",
    "group": "Grupo F",
    "stadium": "Estadio Monterrey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "37",
    "date": "2026-06-21",
    "time": "12:00",
    "homeTeam": "España",
    "awayTeam": "Arabia Saudí",
    "group": "Grupo H",
    "stadium": "Estadio Atlanta",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "38",
    "date": "2026-06-21",
    "time": "15:00",
    "homeTeam": "Bélgica",
    "awayTeam": "Irán",
    "group": "Grupo G",
    "stadium": "Estadio Los Ángeles",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "39",
    "date": "2026-06-21",
    "time": "18:00",
    "homeTeam": "Uruguay",
    "awayTeam": "Cabo Verde",
    "group": "Grupo H",
    "stadium": "Estadio Miami",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "40",
    "date": "2026-06-21",
    "time": "21:00",
    "homeTeam": "Nueva Zelanda",
    "awayTeam": "Egipto",
    "group": "Grupo G",
    "stadium": "Estadio BC Place Vancouver",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "41",
    "date": "2026-06-22",
    "time": "13:00",
    "homeTeam": "Argentina",
    "awayTeam": "Austria",
    "group": "Grupo J",
    "stadium": "Estadio Dallas",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "42",
    "date": "2026-06-22",
    "time": "17:00",
    "homeTeam": "Francia",
    "awayTeam": "Irak",
    "group": "Grupo I",
    "stadium": "Estadio Filadelfia",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "43",
    "date": "2026-06-22",
    "time": "20:00",
    "homeTeam": "Noruega",
    "awayTeam": "Senegal",
    "group": "Grupo I",
    "stadium": "Estadio Nueva York Nueva Jersey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "44",
    "date": "2026-06-22",
    "time": "23:00",
    "homeTeam": "Jordania",
    "awayTeam": "Argelia",
    "group": "Grupo J",
    "stadium": "Estadio Bahía de San Francisco Bay",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "45",
    "date": "2026-06-23",
    "time": "13:00",
    "homeTeam": "Portugal",
    "awayTeam": "Uzbekistán",
    "group": "Grupo K",
    "stadium": "Estadio Houston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "46",
    "date": "2026-06-23",
    "time": "16:00",
    "homeTeam": "Inglaterra",
    "awayTeam": "Ghana",
    "group": "Grupo L",
    "stadium": "Estadio Boston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "47",
    "date": "2026-06-23",
    "time": "19:00",
    "homeTeam": "Panamá",
    "awayTeam": "Croacia",
    "group": "Grupo L",
    "stadium": "Estadio Toronto",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "48",
    "date": "2026-06-23",
    "time": "22:00",
    "homeTeam": "Colombia",
    "awayTeam": "RD Congo",
    "group": "Grupo K",
    "stadium": "Estadio Guadalajara",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "49",
    "date": "2026-06-24",
    "time": "15:00",
    "homeTeam": "Suiza",
    "awayTeam": "Canadá",
    "group": "Grupo B",
    "stadium": "Estadio BC Place Vancouver",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "50",
    "date": "2026-06-24",
    "time": "15:00",
    "homeTeam": "Bosnia y Herzegovina",
    "awayTeam": "Catar",
    "group": "Grupo B",
    "stadium": "Estadio Seattle",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "51",
    "date": "2026-06-24",
    "time": "18:00",
    "homeTeam": "Escocia",
    "awayTeam": "Brasil",
    "group": "Grupo C",
    "stadium": "Estadio Miami",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "52",
    "date": "2026-06-24",
    "time": "18:00",
    "homeTeam": "Marruecos",
    "awayTeam": "Haití",
    "group": "Grupo C",
    "stadium": "Estadio Atlanta",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "53",
    "date": "2026-06-24",
    "time": "21:00",
    "homeTeam": "República Checa",
    "awayTeam": "México",
    "group": "Grupo A",
    "stadium": "Estadio Ciudad de México",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "54",
    "date": "2026-06-24",
    "time": "21:00",
    "homeTeam": "Sudáfrica",
    "awayTeam": "República de Corea",
    "group": "Grupo A",
    "stadium": "Estadio Monterrey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "55",
    "date": "2026-06-25",
    "time": "16:00",
    "homeTeam": "Curazao",
    "awayTeam": "Costa de Marfil",
    "group": "Grupo E",
    "stadium": "Estadio Filadelfia",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "56",
    "date": "2026-06-25",
    "time": "16:00",
    "homeTeam": "Ecuador",
    "awayTeam": "Alemania",
    "group": "Grupo E",
    "stadium": "Estadio Nueva York Nueva Jersey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "57",
    "date": "2026-06-25",
    "time": "19:00",
    "homeTeam": "Japón",
    "awayTeam": "Suecia",
    "group": "Grupo F",
    "stadium": "Estadio Dallas",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "58",
    "date": "2026-06-25",
    "time": "19:00",
    "homeTeam": "Túnez",
    "awayTeam": "Países Bajos",
    "group": "Grupo F",
    "stadium": "Estadio Kansas City",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "59",
    "date": "2026-06-25",
    "time": "22:00",
    "homeTeam": "Turquía",
    "awayTeam": "Estados Unidos",
    "group": "Grupo D",
    "stadium": "Estadio Los Ángeles",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "60",
    "date": "2026-06-25",
    "time": "22:00",
    "homeTeam": "Paraguay",
    "awayTeam": "Australia",
    "group": "Grupo D",
    "stadium": "Estadio Bahía de San Francisco",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "61",
    "date": "2026-06-26",
    "time": "15:00",
    "homeTeam": "Noruega",
    "awayTeam": "Francia",
    "group": "Grupo I",
    "stadium": "Estadio Boston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "62",
    "date": "2026-06-26",
    "time": "15:00",
    "homeTeam": "Senegal",
    "awayTeam": "Irak",
    "group": "Grupo I",
    "stadium": "Estadio Toronto",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "63",
    "date": "2026-06-26",
    "time": "20:00",
    "homeTeam": "Cabo Verde",
    "awayTeam": "Arabia Saudí",
    "group": "Grupo H",
    "stadium": "Estadio Houston",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "64",
    "date": "2026-06-26",
    "time": "20:00",
    "homeTeam": "Uruguay",
    "awayTeam": "España",
    "group": "Grupo H",
    "stadium": "Estadio Guadalajara",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "65",
    "date": "2026-06-26",
    "time": "23:00",
    "homeTeam": "Egipto",
    "awayTeam": "Irán",
    "group": "Grupo G",
    "stadium": "Estadio Seattle",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "66",
    "date": "2026-06-26",
    "time": "23:00",
    "homeTeam": "Nueva Zelanda",
    "awayTeam": "Bélgica",
    "group": "Grupo G",
    "stadium": "Estadio BC Place Vancouver",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "67",
    "date": "2026-06-27",
    "time": "17:00",
    "homeTeam": "Panamá",
    "awayTeam": "Inglaterra",
    "group": "Grupo L",
    "stadium": "Estadio Nueva York Nueva Jersey",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "68",
    "date": "2026-06-27",
    "time": "17:00",
    "homeTeam": "Croacia",
    "awayTeam": "Ghana",
    "group": "Grupo L",
    "stadium": "Estadio Filadelfia",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "69",
    "date": "2026-06-27",
    "time": "19:30",
    "homeTeam": "Colombia",
    "awayTeam": "Portugal",
    "group": "Grupo K",
    "stadium": "Estadio Miami",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "70",
    "date": "2026-06-27",
    "time": "19:30",
    "homeTeam": "RD Congo",
    "awayTeam": "Uzbekistán",
    "group": "Grupo K",
    "stadium": "Estadio Atlanta",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "71",
    "date": "2026-06-27",
    "time": "22:00",
    "homeTeam": "Argelia",
    "awayTeam": "Austria",
    "group": "Grupo J",
    "stadium": "Estadio Kansas City",
    "stage": "group",
    "isCompleted": false
  },
  {
    "id": "72",
    "date": "2026-06-27",
    "time": "22:00",
    "homeTeam": "Jordania",
    "awayTeam": "Argentina",
    "group": "Grupo J",
    "stadium": "Estadio Dallas",
    "stage": "group",
    "isCompleted": false
  }
];
