import { Match } from '../types';

export const MATCHES: Match[] = [
  {
    id: '1',
    date: '2026-06-11',
    time: '15:00',
    homeTeam: 'MEX',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '2',
    date: '2026-06-11',
    time: '18:00',
    homeTeam: 'USA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '3',
    date: '2026-06-11',
    time: '21:00',
    homeTeam: 'CAN',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '4',
    date: '2026-06-12',
    time: '12:00',
    homeTeam: 'BRA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '5',
    date: '2026-06-12',
    time: '15:00',
    homeTeam: 'ARG',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '6',
    date: '2026-06-12',
    time: '18:00',
    homeTeam: 'GER',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '7',
    date: '2026-06-12',
    time: '21:00',
    homeTeam: 'FRA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '8',
    date: '2026-06-13',
    time: '12:00',
    homeTeam: 'ENG',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '9',
    date: '2026-06-13',
    time: '15:00',
    homeTeam: 'ESP',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '10',
    date: '2026-06-13',
    time: '18:00',
    homeTeam: 'NED',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '11',
    date: '2026-06-13',
    time: '21:00',
    homeTeam: 'ITA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '12',
    date: '2026-06-14',
    time: '12:00',
    homeTeam: 'POR',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '13',
    date: '2026-06-14',
    time: '15:00',
    homeTeam: 'BEL',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '14',
    date: '2026-06-14',
    time: '18:00',
    homeTeam: 'COL',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '15',
    date: '2026-06-14',
    time: '21:00',
    homeTeam: 'URU',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '16',
    date: '2026-06-15',
    time: '12:00',
    homeTeam: 'JPN',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '17',
    date: '2026-06-15',
    time: '15:00',
    homeTeam: 'KOR',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '18',
    date: '2026-06-15',
    time: '18:00',
    homeTeam: 'AUS',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '19',
    date: '2026-06-15',
    time: '21:00',
    homeTeam: 'SUI',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '20',
    date: '2026-06-16',
    time: '12:00',
    homeTeam: 'MAR',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '21',
    date: '2026-06-16',
    time: '15:00',
    homeTeam: 'SEN',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '22',
    date: '2026-06-16',
    time: '18:00',
    homeTeam: 'ECU',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '23',
    date: '2026-06-16',
    time: '21:00',
    homeTeam: 'CRO',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '24',
    date: '2026-06-17',
    time: '12:00',
    homeTeam: 'GER',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '25',
    date: '2026-06-17',
    time: '15:00',
    homeTeam: 'MEX',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '26',
    date: '2026-06-17',
    time: '18:00',
    homeTeam: 'USA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '27',
    date: '2026-06-18',
    time: '12:00',
    homeTeam: 'BRA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '28',
    date: '2026-06-18',
    time: '15:00',
    homeTeam: 'ARG',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '29',
    date: '2026-06-18',
    time: '18:00',
    homeTeam: 'FRA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '30',
    date: '2026-06-19',
    time: '12:00',
    homeTeam: 'ENG',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '31',
    date: '2026-06-19',
    time: '15:00',
    homeTeam: 'ESP',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '32',
    date: '2026-06-19',
    time: '18:00',
    homeTeam: 'NED',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '33',
    date: '2026-06-19',
    time: '21:00',
    homeTeam: 'ITA',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '34',
    date: '2026-06-20',
    time: '12:00',
    homeTeam: 'POR',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '35',
    date: '2026-06-20',
    time: '15:00',
    homeTeam: 'BEL',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
  {
    id: '36',
    date: '2026-06-20',
    time: '18:00',
    homeTeam: 'COL',
    awayTeam: 'TBD',
    stage: 'group',
    isCompleted: false,
  },
];

export const stageLabels: Record<string, string> = {
  group: 'Fase de Grupos',
  round16: 'Octavos',
  quarter: 'Cuartos',
  semi: 'Semifinal',
  final: 'Final',
};

export const groupNames = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
